config/routes.rb
Rails.application.routes.draw do

  get 'tops/index' => 'tops#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :drivings do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :comments
  resources :likes
  
  root 'tops#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :driving
end

app/models/driving.rb
class Driving < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    has_many :driving_genre_relations, dependent: :destroy
    has_many :genres, through: :driving_genre_relations, dependent: :destroy

    geocoded_by :address
    after_validation :geocode, if: :address_changed?
end

app/models/driving_genre_relation.rb
class DrivingGenreRelation < ApplicationRecord
  belongs_to :driving
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :driving_genre_relations, dependent: :destroy
    has_many :drivings, through: :driving_genre_relations, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :driving
  belongs_to :user
  validates_uniqueness_of :driving_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :drivings, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_drivings, through: :likes, source: :driving
  has_many :comments, dependent: :destroy

  def already_liked?(driving)
    self.likes.exists?(driving_id: driving.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def new
  end

  def create
    driving = Driving.find(params[:driving_id])
    comment = driving.comments.build(comment_params) #buildを使い、contentとdriving_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
  end

  def edit
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/drivings_controller.rb
class DrivingsController < ApplicationController
  before_action :authenticate_user!

  #arr = [a,b,c]
  #hash = {タグ１: 1, タグ２: 0, たぐ３: 1}

  def index
    @drivings = Driving.all
    @drivings = @drivings.where("destination LIKE ? ",'%' + params[:destination_search] + '%') if params[:destination_search]
    @drivings = @drivings.where("address LIKE ? ",'%' + params[:address_search] + '%') if params[:address_search]
    
    if params[:genre_ids]
      genre_driving_ids = [] #idは配列
      params[:genre_ids].each do |key, value|   #ハッシュを持ってくるため変数2つ   
        if value == "1" #チェック済
          Genre.find_by(name: key).drivings.each do |driving|
            genre_driving_ids << driving.id
          end
          @drivings = @drivings.where(id: genre_driving_ids)
        end
      end
    end

    if params[:genre]
      Genre.create(name: params[:genre])
    end

    @rank_drivings = @drivings.sort {|a,b| b.liked_users.count <=> a.liked_users.count}
  
    @genres = Genre.all
  
  end

  def new
    @driving = Driving.new
    @drivings = Driving.where(user_id: current_user.id).all
  end

  def create
    driving = Driving.new(driving_params)
    driving.user_id = current_user.id

    if driving.save
      redirect_to :action => "new"
    else
      redirect_to :action => "new"
    end
  end

  def edit
    @driving = Driving.find(params[:id])
  end

  def update
    driving = Driving.find(params[:id])
    if driving.update(driving_params)
      redirect_to :action => "new"
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    driving = Driving.find(params[:id])
    driving.destroy
    redirect_to action: :new
  end

  def show
    @driving = Driving.find(params[:id])
    @comments = @driving.comments
    @comment = Comment.new
  end

  private
  def driving_params
    params.require(:driving).permit(:destination, :image, :body, :address, genre_ids:[])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.create(driving_id: params[:driving_id]) #user_idとdriving_idの二つを代入
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(driving_id: params[:driving_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @likespots = current_user.liked_drivings.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/drivings_helper.rb
module DrivingsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/drivings/create.html.erb
<h1>Drivings#create</h1>
<p>Find me in app/views/drivings/create.html.erb</p>

app/views/drivings/destroy.html.erb
<h1>Drivings#destroy</h1>
<p>Find me in app/views/drivings/destroy.html.erb</p>

app/views/drivings/edit.html.erb
<h1>投稿の編集</h1>

<%= form_for @driving do |f| %>
  <p><%= f.label :spot %>
  <%= f.text_field :destination, :size => 50 %></p> 
  <div class='form-group'>
  <p>ジャンル</p>
        <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) do |genre| %>
            <div class='form-check'>
                <%= genre.label class: 'form-check-label' do %>
                    <%= genre.check_box class: 'form-check-input' %>
                    <%= genre.text %>
                <% end %>
            </div>
        <% end %>
  </div>
  <p><%= f.label :image %>
  <%= f.file_field :image %></p>
  <p><%= f.label :body %>
  <%= f.text_area :body, :size =>"70x10" %></p>
  <p><%= f.label :address %>
  （正確にお願いします！）
  <%= f.text_field :address, :size => 100 %></p>
  <%= f.submit "編集する" %>
<% end %>
<%= link_to "戻る", new_driving_path %>

app/views/drivings/index.html.erb
<% if user_signed_in? %>
<%= link_to "マイページへ", user_path(current_user.id) %>

<h2>検索ページ</h2>
<%= form_tag({controller:"drivings",action:"index"}, method: :get) do %>
   <b>スポット名</b>
   <%= text_field_tag :destination_search %>
   <%= submit_tag '検索する'  %>

   <p>
   <b>ジャンル</b>
   <% @genres.each do |t| %>
        <li><%= check_box :genre_ids, t.name %><%= t.name %></li>
   <% end %>
   </p>

   <p>
   <b>所在地（キーワード）</b>
   <%= text_field_tag :address_search %>
   </p>

   <%= submit_tag '検索する'  %>
<% end %>

<h2>スポット一覧</h2>
<div class="drivings-container">
  <% @drivings.each do |d| %>
  <div class="driving">
    <p><%= image_tag d.image_url, size: "150x100" if d.image? %>
    <%= d.destination %></p>
    <p><%= d.body %></p>
    <p>所在地：<%= d.address %></p>
    <i class="far fa-heart"></i><%= d.likes.count %>
    <%= link_to "詳細へ", driving_path(d.id) %>
  </div>
  <% end %>
  <% @rank_drivings.each do |d| %>
  <% end %>
</div>

<% end %>

<script>
function geoFindMe() {

  const status = document.querySelector('#status');
  const mapLink = document.querySelector('#map-link');

  mapLink.href = '';
  mapLink.textContent = '';

  function success(position) {
    const latitude  = position.coords.latitude;
    const longitude = position.coords.longitude;

    status.textContent = '';
    mapLink.href = `https://www.openstreetmap.org/#map=18/${latitude}/${longitude}`;
    mapLink.textContent = `Latitude: ${latitude} °, Longitude: ${longitude} °`;
  }

  function error() {
    status.textContent = 'Unable to retrieve your location';
  }

  if(!navigator.geolocation) {
    status.textContent = 'Geolocation is not supported by your browser';
  } else {
    status.textContent = 'Locating…';
    navigator.geolocation.getCurrentPosition(success, error);
  }

}

document.querySelector('#find-me').addEventListener('click', geoFindMe);

</script>

app/views/drivings/new.html.erb
<% if user_signed_in? %>
<%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>

<h1>スポット投稿</h1>

<h3>新規投稿</h3>
<%= form_for @driving do |f| %>

  <div class="field">
    <%= f.label :destination %>
    <%= f.text_field :destination, :size => 50 %>
  </div>

  <div class='form-group'>
  <p>ジャンル</p>
        <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) do |genre| %>
            <div class='form-check'>
                <%= genre.label class: 'form-check-label' do %>
                    <%= genre.check_box class: 'form-check-input' %>
                    <%= genre.text %>
                <% end %>
            </div>
        <% end %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, :size =>"70x10" %>
  </div>
  <div class="field">
    <%= f.label :address %>
    （正確にお願いします！）
    <%= f.text_field :address, :size => 100 %>
  </div>

  <%= f.submit "投稿する" %>
<% end %>

  <div class="drivings-container">
    <h1>自分の投稿</h1>
    <% @drivings.each do |d| %>
        <div class="driving">
          <p><%= image_tag d.image_url, size: "150x100" if d.image? %>
          <%= d.destination %></p>
          <p><%= d.body %></p>
          <p>所在地：<%= d.address %></p>
        </div>
        <%= link_to "編集する", edit_driving_path(d.id) %>
        <%= button_to "削除する", driving_path(d.id), method: :delete %>
      <% end %>
  </div>

app/views/drivings/show.html.erb
<%= link_to "マイページへ", user_path(current_user.id) %>
<h3>スポット詳細</h3>
<div class="driving">
  <% @driving.genres.each do |genre| %>
    <span><%= genre.name %></span>
  <% end %>

  <p><%= @driving.destination %></p>
  <p><%= image_tag @driving.image_url, size: "300x200" if @driving.image? %></p>
  <p><%= @driving.body %></p>
  <p>所在地：<%= @driving.address %></p>
  <p><%= @driving.created_at %></p>

<% if user_signed_in? %>
      <% if current_user.already_liked?(@driving) %>
          <%= link_to driving_like_path(@driving), method: :delete do %>
             <i class="fas fa-heart"></i><%= @driving.likes.count %>
          <% end %>
      <% else %>
          <%= link_to driving_likes_path(@driving), method: :post do %>
             <i class="far fa-heart"></i><%= @driving.likes.count %>
          <% end %>
      <% end %>
  <% else %>
      <i class="far fa-heart"></i><%= @driving.likes.count %>
  <% end %>
</div>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.name unless c.user.blank? %>:
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@driving, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
<%= link_to "スポット一覧に戻る", drivings_path %>


<div id="routelink">    
    <a id="link" href="#" target="_blank">経路</a>
</div>
<p id = "status"></p>

<script>
  const status = document.querySelector('#status');
  
  function success(position) {
    const latitude  = position.coords.latitude;
    const longitude = position.coords.longitude;

    status.textContent = '';
   
    let link = document.getElementById('link');
    let url = `https://www.google.com/maps/dir/${latitude},${longitude}/<%= @driving.address %>`;

    console.log(latitude)
    console.log(longitude)
    link.setAttribute('href', url);
  }

  function error() {
    status.textContent = 'Unable to retrieve your location';
  }

  if(!navigator.geolocation) {
    status.textContent = 'Geolocation is not supported by your browser';
  } else {
    status.textContent = 'Locating…';
    navigator.geolocation.getCurrentPosition(success, error);
  }
</script>

<iframe src="https://maps.google.co.jp/maps?output=embed&q=<%= @driving.address %>&z=13" width="600" height="400" frameborder="0" scrolling="no" ></iframe>

<a href= "https://maps.googleapis.com/maps/api/directions/json?origin=Toronto&destination=Montreal&key=api" target="_blank" >別ウインドウで開くリンク</a>

<script>
require 'net/http'
require 'uri'
require 'json'

uri = URI.parse(`https://maps.googleapis.com/maps/api/directions/json?origin=${latitude},${longitude}&destination=<%= @driving.address %>&key=api`)
json = Net::HTTP.get(uri)
purse = JSON.parse(json)
result = console.log(json.routes.legs.duration.text)
</script>

app/views/drivings/update.html.erb
<h1>Drivings#update</h1>
<p>Find me in app/views/drivings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drivespot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/tops/index.html.erb
<%= link_to "ログイン", drivings_path %>
<%= link_to "新規登録", new_user_registration_path %>

<%= link_to '探す', drivings_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>マイページ</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<%= link_to '探す', drivings_path %>
<%= link_to '新規投稿・投稿一覧', new_driving_path %>

<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>

<div class="likespots-container">
    <h3>お気に入りスポット</h3>
    <% @likespots.each do |d| %>
        <div class="driving">
          <p><%= image_tag d.image_url, size: "150x100" if d.image? %>
          <%= d.destination %></p>
          <p>所在地：<%= d.address %></p>
          <%= link_to "詳細へ", driving_path(d.id) %>
        </div>
    <% end %>
  </div>